/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.du.tranlam;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author Lam Tran
 */
public class DiceView extends javax.swing.JFrame {
    final int DEFAULT_NUMBER_OF_SIDES = 6;
    final int DEFAULT_NUMBER_OF_ROLLS = 1;
    private ArrayList<ImageIcon> diceIconList = new ArrayList<>();
    Dice dice1 = new Dice(DEFAULT_NUMBER_OF_SIDES);
    Dice dice2 = new Dice(DEFAULT_NUMBER_OF_SIDES);
    int sum = 0;
    int rolls;
    ArrayList<JTextField> countArrayList = new ArrayList<>();
    ArrayList<JTextField> percentArrayList = new ArrayList<>();
    static int[] valueArray;
    
    
    /**
     * Creates new form DiceView
     */
    public DiceView() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension windowSize = new Dimension((screenSize.width/2) + 100, (screenSize.height/2) + 100);
        setPreferredSize(windowSize);
        setLocation (((screenSize.width - windowSize.width)/2),((screenSize.height - windowSize.height)/2));

        setTitle("Roll the Dice");
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        valueArray = new int[DEFAULT_NUMBER_OF_SIDES*2];
        
        diceIconList.add(0,new ImageIcon("dice1.jpg"));
        diceIconList.add(1,new ImageIcon("dice2.jpg"));
        diceIconList.add(2,new ImageIcon("dice3.jpg"));
        diceIconList.add(3,new ImageIcon("dice4.jpg"));
        diceIconList.add(4,new ImageIcon("dice5.jpg"));
        diceIconList.add(5,new ImageIcon("dice6.jpg"));
        
        //build arraylist for count and % here
        
        countArrayList.add(textFieldOf1);
        countArrayList.add(textFieldOf2);
        countArrayList.add(textFieldOf3);
        countArrayList.add(textFieldOf4);
        countArrayList.add(textFieldOf5);
        countArrayList.add(textFieldOf6);
        countArrayList.add(textFieldOf7);
        countArrayList.add(textFieldOf8);
        countArrayList.add(textFieldOf9);
        countArrayList.add(textFieldOf10);
        countArrayList.add(textFieldOf11);
        countArrayList.add(textFieldOf12);
        
        
        percentArrayList.add(percentOf1);
        percentArrayList.add(percentOf2);
        percentArrayList.add(percentOf3);
        percentArrayList.add(percentOf4);
        percentArrayList.add(percentOf5);
        percentArrayList.add(percentOf6);
        percentArrayList.add(percentOf7);
        percentArrayList.add(percentOf8);
        percentArrayList.add(percentOf9);
        percentArrayList.add(percentOf10);
        percentArrayList.add(percentOf11);
        percentArrayList.add(percentOf12);
        
        rolls = 0;
        
        dice1Label.setIcon(diceIconList.get(0));
        dice2Label.setIcon(diceIconList.get(2));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rollButton = new javax.swing.JButton();
        sumLabel = new javax.swing.JLabel();
        dice1Label = new javax.swing.JLabel();
        sumTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        javax.swing.JLabel numberOf2 = new javax.swing.JLabel();
        javax.swing.JLabel numberOf1 = new javax.swing.JLabel();
        javax.swing.JLabel numberOf3 = new javax.swing.JLabel();
        javax.swing.JLabel numberOf4 = new javax.swing.JLabel();
        javax.swing.JLabel numberOf5 = new javax.swing.JLabel();
        javax.swing.JLabel numberOf6 = new javax.swing.JLabel();
        javax.swing.JLabel numberOf7 = new javax.swing.JLabel();
        javax.swing.JLabel numberOf8 = new javax.swing.JLabel();
        javax.swing.JLabel numberOf9 = new javax.swing.JLabel();
        javax.swing.JLabel numberOf10 = new javax.swing.JLabel();
        javax.swing.JLabel numberOf11 = new javax.swing.JLabel();
        textFieldOf12 = new javax.swing.JTextField();
        textFieldOf1 = new javax.swing.JTextField();
        textFieldOf2 = new javax.swing.JTextField();
        textFieldOf3 = new javax.swing.JTextField();
        textFieldOf4 = new javax.swing.JTextField();
        textFieldOf5 = new javax.swing.JTextField();
        textFieldOf6 = new javax.swing.JTextField();
        textFieldOf7 = new javax.swing.JTextField();
        textFieldOf8 = new javax.swing.JTextField();
        textFieldOf10 = new javax.swing.JTextField();
        textFieldOf9 = new javax.swing.JTextField();
        textFieldOf11 = new javax.swing.JTextField();
        percentageLabel = new javax.swing.JLabel();
        percentOf1 = new javax.swing.JTextField();
        percentOf2 = new javax.swing.JTextField();
        percentOf3 = new javax.swing.JTextField();
        percentOf4 = new javax.swing.JTextField();
        percentOf5 = new javax.swing.JTextField();
        percentOf6 = new javax.swing.JTextField();
        percentOf7 = new javax.swing.JTextField();
        percentOf8 = new javax.swing.JTextField();
        percentOf9 = new javax.swing.JTextField();
        percentOf10 = new javax.swing.JTextField();
        percentOf11 = new javax.swing.JTextField();
        percentOf12 = new javax.swing.JTextField();
        javax.swing.JLabel numberOf12 = new javax.swing.JLabel();
        dice2Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rollButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        rollButton.setText("Roll");
        rollButton.setToolTipText("Roll those Dice!");
        rollButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray));
        rollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollButtonActionPerformed(evt);
            }
        });

        sumLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        sumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sumLabel.setText("Sum");
        sumLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.white));

        dice1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dice1Label.setText("d1");
        dice1Label.setToolTipText("Dice 1");

        sumTextField.setEditable(false);
        sumTextField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        sumTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sumTextField.setText("0");
        sumTextField.setToolTipText("Sum Rolled");
        sumTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));

        clearButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        clearButton.setText("Clear");
        clearButton.setToolTipText("Clear the scores");
        clearButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        numberOf2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        numberOf2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOf2.setText("Number of 2's");
        numberOf2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        numberOf2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        numberOf1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        numberOf1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOf1.setText("Number of 1's");
        numberOf1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        numberOf3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        numberOf3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOf3.setText("Number of 3's");
        numberOf3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        numberOf4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        numberOf4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOf4.setText("Number of 4's");
        numberOf4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        numberOf5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        numberOf5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOf5.setText("Number of 5's");
        numberOf5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        numberOf6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        numberOf6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOf6.setText("Number of 6's");
        numberOf6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        numberOf7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        numberOf7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOf7.setText("Number of 7's");
        numberOf7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        numberOf8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        numberOf8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOf8.setText("Number of 8's");
        numberOf8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        numberOf9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        numberOf9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOf9.setText("Number of 9's");
        numberOf9.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        numberOf10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        numberOf10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOf10.setText("Number of 10's");
        numberOf10.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        numberOf11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        numberOf11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOf11.setText("Number of 11's");
        numberOf11.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        textFieldOf12.setEditable(false);
        textFieldOf12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textFieldOf12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldOf12.setText("0");
        textFieldOf12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));

        textFieldOf1.setEditable(false);
        textFieldOf1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textFieldOf1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldOf1.setText("0");
        textFieldOf1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));

        textFieldOf2.setEditable(false);
        textFieldOf2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textFieldOf2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldOf2.setText("0");
        textFieldOf2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));

        textFieldOf3.setEditable(false);
        textFieldOf3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textFieldOf3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldOf3.setText("0");
        textFieldOf3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));

        textFieldOf4.setEditable(false);
        textFieldOf4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textFieldOf4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldOf4.setText("0");
        textFieldOf4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));

        textFieldOf5.setEditable(false);
        textFieldOf5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textFieldOf5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldOf5.setText("0");
        textFieldOf5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));

        textFieldOf6.setEditable(false);
        textFieldOf6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textFieldOf6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldOf6.setText("0");
        textFieldOf6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));

        textFieldOf7.setEditable(false);
        textFieldOf7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textFieldOf7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldOf7.setText("0");
        textFieldOf7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));

        textFieldOf8.setEditable(false);
        textFieldOf8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textFieldOf8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldOf8.setText("0");
        textFieldOf8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));

        textFieldOf10.setEditable(false);
        textFieldOf10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textFieldOf10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldOf10.setText("0");
        textFieldOf10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));

        textFieldOf9.setEditable(false);
        textFieldOf9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textFieldOf9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldOf9.setText("0");
        textFieldOf9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));

        textFieldOf11.setEditable(false);
        textFieldOf11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textFieldOf11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldOf11.setText("0");
        textFieldOf11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));

        percentageLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        percentageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        percentageLabel.setText("Percentage");

        percentOf1.setEditable(false);
        percentOf1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        percentOf1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentOf1.setText("0");
        percentOf1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        percentOf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentOf1ActionPerformed(evt);
            }
        });

        percentOf2.setEditable(false);
        percentOf2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        percentOf2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentOf2.setText("0");
        percentOf2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        percentOf3.setEditable(false);
        percentOf3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        percentOf3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentOf3.setText("0");
        percentOf3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        percentOf4.setEditable(false);
        percentOf4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        percentOf4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentOf4.setText("0");
        percentOf4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        percentOf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentOf4ActionPerformed(evt);
            }
        });

        percentOf5.setEditable(false);
        percentOf5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        percentOf5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentOf5.setText("0");
        percentOf5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        percentOf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentOf5ActionPerformed(evt);
            }
        });

        percentOf6.setEditable(false);
        percentOf6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        percentOf6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentOf6.setText("0");
        percentOf6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        percentOf7.setEditable(false);
        percentOf7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        percentOf7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentOf7.setText("0");
        percentOf7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        percentOf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentOf7ActionPerformed(evt);
            }
        });

        percentOf8.setEditable(false);
        percentOf8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        percentOf8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentOf8.setText("0");
        percentOf8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        percentOf9.setEditable(false);
        percentOf9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        percentOf9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentOf9.setText("0");
        percentOf9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        percentOf10.setEditable(false);
        percentOf10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        percentOf10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentOf10.setText("0");
        percentOf10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        percentOf11.setEditable(false);
        percentOf11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        percentOf11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentOf11.setText("0");
        percentOf11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        percentOf12.setEditable(false);
        percentOf12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        percentOf12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentOf12.setText("0");
        percentOf12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        percentOf12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentOf12ActionPerformed(evt);
            }
        });

        numberOf12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        numberOf12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOf12.setText("Number of 12's");
        numberOf12.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        dice2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dice2Label.setText("d2");
        dice2Label.setToolTipText("Dice 1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(58, 58, 58)
                                    .addComponent(dice1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(sumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dice2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(sumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(25, 25, 25))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(rollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numberOf12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOf11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOf10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOf9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOf8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOf7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOf6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOf5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOf4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOf3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOf2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOf1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldOf1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOf2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOf3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOf4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOf5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOf6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOf7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOf8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOf9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOf10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOf11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOf12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(percentOf1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentOf3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentOf2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentOf4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentOf5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentOf6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentOf7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentOf8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentOf9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentOf10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentOf11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentOf12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(percentageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(percentageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(percentOf1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldOf1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numberOf1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(percentOf2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textFieldOf2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberOf2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textFieldOf3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(percentOf3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(numberOf3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOf4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldOf4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentOf4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOf5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldOf5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentOf5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldOf6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentOf6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOf6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOf7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldOf7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentOf7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(dice2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dice1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(numberOf8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldOf8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(percentOf8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(numberOf9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldOf9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(percentOf9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOf10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldOf10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentOf10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOf11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldOf11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentOf11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOf12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldOf12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentOf12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollButtonActionPerformed
              
        sum = 0;
        dice1.roll();
        dice2.roll();
        dice1Label.setIcon(diceIconList.get(dice1.getNumberShowing()-1));
        dice2Label.setIcon(diceIconList.get(dice2.getNumberShowing()-1));
        sum = dice1.getNumberShowing() + dice2.getNumberShowing();
        
        switch(sum){
            case 12:
                jLabel1.setText("You see me rollin', you hatin' ");
                break;
            case 2:
                jLabel1.setText("Snake Eyes!");
                break;
            case 10:
                jLabel1.setText("10/10 Hope it's my grade too!");
                break;
            default:
                jLabel1.setText (" ");
        }
        valueArray[sum -1]++;
        rolls++;
        sumTextField.setText(String.valueOf(sum));
        countArrayList.get(sum -1).setText(String.valueOf(valueArray[sum -1]));
        
        //update the 2 arraylist base on what sum shows up
        for(int i = 0; i<percentArrayList.size(); i++){
        percentArrayList.get(i).setText(String.format("%.2f",((double)(valueArray[i]*100/rolls))) + "%");
        }
    }//GEN-LAST:event_rollButtonActionPerformed

    private void percentOf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentOf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentOf1ActionPerformed

    private void percentOf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentOf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentOf4ActionPerformed

    private void percentOf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentOf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentOf7ActionPerformed

    private void percentOf12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentOf12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentOf12ActionPerformed

    private void percentOf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentOf5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentOf5ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
 
    for(int i = 0; i < valueArray.length; i++) {
        valueArray[i] = 0; 
        countArrayList.get(i).setText("0");
        percentArrayList.get(i).setText("0.00%");
    }
    rolls = 0;
    
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel dice1Label;
    private javax.swing.JLabel dice2Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField percentOf1;
    private javax.swing.JTextField percentOf10;
    private javax.swing.JTextField percentOf11;
    private javax.swing.JTextField percentOf12;
    private javax.swing.JTextField percentOf2;
    private javax.swing.JTextField percentOf3;
    private javax.swing.JTextField percentOf4;
    private javax.swing.JTextField percentOf5;
    private javax.swing.JTextField percentOf6;
    private javax.swing.JTextField percentOf7;
    private javax.swing.JTextField percentOf8;
    private javax.swing.JTextField percentOf9;
    private javax.swing.JLabel percentageLabel;
    private javax.swing.JButton rollButton;
    private javax.swing.JLabel sumLabel;
    private javax.swing.JTextField sumTextField;
    private javax.swing.JTextField textFieldOf1;
    private javax.swing.JTextField textFieldOf10;
    private javax.swing.JTextField textFieldOf11;
    private javax.swing.JTextField textFieldOf12;
    private javax.swing.JTextField textFieldOf2;
    private javax.swing.JTextField textFieldOf3;
    private javax.swing.JTextField textFieldOf4;
    private javax.swing.JTextField textFieldOf5;
    private javax.swing.JTextField textFieldOf6;
    private javax.swing.JTextField textFieldOf7;
    private javax.swing.JTextField textFieldOf8;
    private javax.swing.JTextField textFieldOf9;
    // End of variables declaration//GEN-END:variables
}